const MAX_EVENTS_PER_TICK = 32;
const MAX_MIDI_MESSAGES_PER_SECOND = 1000;
const MAX_ARP_STATE_ENTRIES = 256;
const MAX_REPEAT_HISTORY_KEYS = 512;

export {
  MAX_ARP_STATE_ENTRIES,
  MAX_EVENTS_PER_TICK,
  MAX_MIDI_MESSAGES_PER_SECOND,
  MAX_REPEAT_HISTORY_KEYS
};
