const DEFAULT_LEVEL_WIDTH = 1600;
const DEFAULT_LEVEL_HEIGHT = 160;
const LEVEL_FILE_SIZE = 2048;

const LEVEL_OBJECT_COUNT = 32;
const LEVEL_TERRAIN_COUNT = 400;
const LEVEL_STEEL_COUNT = 32;
const LEVEL_NAME_LENGTH = 32;

const LEVEL_OBJECT_OFFSET = 0x0020;
const LEVEL_TERRAIN_OFFSET = 0x0120;
const LEVEL_STEEL_OFFSET = 0x0760;
const LEVEL_NAME_OFFSET = 0x07E0;

const OBJECT_X_OFFSET = 16;
const TERRAIN_X_OFFSET = 16;
const TERRAIN_X_MASK = 0x0FFF;
const TERRAIN_Y_OFFSET = 4;
const TERRAIN_Y_WRAP = 512;
const TERRAIN_Y_MASK = 0x01FF;
const TERRAIN_Y_WRAP_THRESHOLD = 256;
const TERRAIN_ID_MASK = 0x003F;
const TERRAIN_FLAG_SHIFT = 29;

const STEEL_X_OFFSET = 16;
const STEEL_X_OFFSET_LEMEDIT = 12;

export {
  DEFAULT_LEVEL_WIDTH,
  DEFAULT_LEVEL_HEIGHT,
  LEVEL_FILE_SIZE,
  LEVEL_OBJECT_COUNT,
  LEVEL_TERRAIN_COUNT,
  LEVEL_STEEL_COUNT,
  LEVEL_NAME_LENGTH,
  LEVEL_OBJECT_OFFSET,
  LEVEL_TERRAIN_OFFSET,
  LEVEL_STEEL_OFFSET,
  LEVEL_NAME_OFFSET,
  OBJECT_X_OFFSET,
  TERRAIN_X_OFFSET,
  TERRAIN_X_MASK,
  TERRAIN_Y_OFFSET,
  TERRAIN_Y_WRAP,
  TERRAIN_Y_MASK,
  TERRAIN_Y_WRAP_THRESHOLD,
  TERRAIN_ID_MASK,
  TERRAIN_FLAG_SHIFT,
  STEEL_X_OFFSET,
  STEEL_X_OFFSET_LEMEDIT
};
