"""Import three authored eight-keyframe RGBA dance sheets into indexed sprites.
Requires Pillow, numpy and scipy. Uses original alpha, uniform scaling and foot
registration only: no per-row warp, pose synthesis or rubber-sheet deformation.
"""
from pathlib import Path
import json, base64
import numpy as np
from scipy.ndimage import label
from PIL import Image
root = Path(__file__).resolve().parent.parent
sources = [('shimmy','source.png'),('charleston','source-charleston.png'),('kickline','source-kickline.png')]
loops, metadata = [], []
for name, filename in sources:
    rgba = np.array(Image.open(root/'assets/decorations/hydro-revue'/filename).convert('RGBA'))
    labels, _ = label(rgba[:,:,3] > 100)
    counts = np.bincount(labels.ravel())
    identifiers = [i for i in range(1,len(counts)) if counts[i] > 1000]
    if len(identifiers) != 8: raise ValueError(f'{filename}: expected 8 full articulated figures, found {len(identifiers)}')
    sprites = {}
    for identifier in identifiers:
        ys,xs = np.where(labels == identifier)
        row = int(ys.mean() >= rgba.shape[0]/2); col = min(3,int(xs.mean()/(rgba.shape[1]/4)))
        index = row*4+col
        if index in sprites: raise ValueError(f'{filename}: multiple figures assigned to cell {index}')
        sprites[index] = (identifier,int(xs.min()),int(ys.min()),int(xs.max())+1,int(ys.max())+1,col)
    if sorted(sprites) != list(range(8)): raise ValueError(f'{filename}: incomplete keyframe grid')
    max_height = max(y1-y0 for _,x0,y0,x1,y1,col in sprites.values())
    half_width = max(max(abs(x0-(col+.5)*rgba.shape[1]/4),abs(x1-(col+.5)*rgba.shape[1]/4)) for _,x0,y0,x1,y1,col in sprites.values())
    scale = min(184/max_height,88/max(1,half_width))
    frames=[]; bounds=[]
    for index in range(8):
        identifier,x0,y0,x1,y1,col = sprites[index]
        pixels=rgba[y0:y1,x0:x1].copy(); mask=labels[y0:y1,x0:x1]==identifier
        pixels[:,:,3]=np.where(mask,pixels[:,:,3],0)
        frame=Image.fromarray(pixels).resize((max(1,round((x1-x0)*scale)),max(1,round((y1-y0)*scale))),Image.Resampling.LANCZOS)
        cell=Image.new('RGBA',(192,192)); ox=round(96+(x0-(col+.5)*rgba.shape[1]/4)*scale); oy=188-frame.height
        cell.alpha_composite(frame,(ox,oy)); frames.append(cell); bounds.append([x0,y0,x1,y1])
    loops.append(frames); metadata.append({'id':name,'source':f'assets/decorations/hydro-revue/{filename}','keyframes':8,'grid':[4,2],'uniformScale':scale,'sourceBounds':bounds,'registration':'fixed grid-column center; supporting-foot baseline y=188'})
combined=Image.new('RGB',(192*8,192*3),'#120b12')
for row,frames in enumerate(loops):
    for col,frame in enumerate(frames): combined.paste(frame,(col*192,row*192),frame)
quantized=combined.quantize(colors=127,method=Image.Quantize.MEDIANCUT)
palette=quantized.getpalette()[:127*3]; colors=['#%02x%02x%02x'%tuple(palette[i:i+3]) for i in range(0,len(palette),3)]
def encode_runs(raw):
    runs=bytearray(); start=0
    while start<len(raw):
        end=start+1
        while end<len(raw) and raw[end]==raw[start] and end-start<255: end+=1
        runs.extend((end-start,raw[start])); start=end
    return base64.b64encode(runs).decode('ascii')
encoded=[]
for row,frames in enumerate(loops):
    keys=[]
    for col,frame in enumerate(frames):
        indices=np.array(quantized.crop((col*192,row*192,(col+1)*192,(row+1)*192)))
        indices[np.array(frame)[:,:,3]<100]=128
        keys.append(encode_runs(indices.tobytes()))
    encoded.append({'id':sources[row][0],'keyframes':keys})
data={'format':'hydro-articulated-loops-v2','encoding':'rle8','width':192,'height':192,'palette':colors,'holdTicks':2,'loops':encoded,'provenance':metadata}
(root/'js/decorations/HydroRevuePixels.js').write_text('// Generated by tools/importHydroRevue.py from authored articulated pose sheets.\nexport const HYDRO_REVUE_PIXELS = '+json.dumps(data,separators=(',',':'))+';\n')
for row,frames in enumerate(loops): frames[0].save(root/f'assets/decorations/hydro-revue/pose-{row}.png')
combined.save(root/'docs/previews/hydro-articulated-keyframes.png')
print('Imported 24 actual pose keyframes; baseline-registered, no deformation. Runtime holds each for 2 ticks.')
