"""Convert the approved generated RGBA sprite sheet to indexed runtime poses.
Requires Pillow, numpy and scipy. No aesthetic background removal is performed:
connected components use the image generator's original alpha channel.
"""
from pathlib import Path
import json, base64
import numpy as np
from scipy.ndimage import label
from PIL import Image
root = Path(__file__).resolve().parent.parent
source = Image.open(root / 'assets/decorations/hydro-revue/source.png').convert('RGBA')
rgba = np.array(source)
labels, _ = label(rgba[:, :, 3] > 100)
counts = np.bincount(labels.ravel()); ids = sorted(range(1, len(counts)), key=lambda i: counts[i], reverse=True)[:3]
ids.sort(key=lambda i: np.where(labels == i)[1].mean())
poses = []
for identifier in ids:
    ys, xs = np.where(labels == identifier)
    cropped = rgba[ys.min():ys.max()+1, xs.min():xs.max()+1].copy()
    mask = labels[ys.min():ys.max()+1, xs.min():xs.max()+1] == identifier
    cropped[:, :, 3] = np.where(mask, cropped[:, :, 3], 0)
    image = Image.fromarray(cropped).resize((round(cropped.shape[1]*184/cropped.shape[0]), 184), Image.Resampling.LANCZOS)
    cell = Image.new('RGBA', (192, 192)); cell.alpha_composite(image, ((192-image.width)//2, 6)); poses.append(cell)
combined = Image.new('RGB', (192*3,192), '#120b12')
for i, image in enumerate(poses): combined.paste(image, (i*192,0), image)
quantized = combined.quantize(colors=127, method=Image.Quantize.MEDIANCUT)
palette = quantized.getpalette()[:127*3]
colors = ['#%02x%02x%02x' % tuple(palette[i:i+3]) for i in range(0,len(palette),3)]
arrays=[]
for i, image in enumerate(poses):
    indexed = np.array(quantized.crop((i*192,0,(i+1)*192,192)))
    indexed[np.array(image)[:,:,3] < 100] = 128
    arrays.append(base64.b64encode(indexed.tobytes()).decode('ascii'))
data={'width':192,'height':192,'palette':colors,'poses':arrays,'source':'assets/decorations/hydro-revue/source.png','generation':'OpenAI imagegen; transparent three-pose sheet; imported using authored alpha'}
(root/'js/decorations/HydroRevuePixels.js').write_text('// Generated by tools/importHydroRevue.py from the approved raster asset.\nexport const HYDRO_REVUE_PIXELS = '+json.dumps(data,separators=(',',':'))+';\n')
for i,p in enumerate(poses): p.save(root/f'assets/decorations/hydro-revue/pose-{i}.png')
