name: Auto-merge repository history

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Sync tools from master
        run: |
          git fetch origin master
          git checkout origin/master -- tools

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

      - name: Compute merge-base
        id: mergebase
        run: |
          echo "MERGE_BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})" >> $GITHUB_OUTPUT

      - name: Merge metrics.json
        run: |
          mkdir -p tmp_merge
          git show ${{ steps.mergebase.outputs.MERGE_BASE }}:.repoMetrics/metrics.json > tmp_merge/base_metrics.json 2>/dev/null || echo '{}' > tmp_merge/base_metrics.json
          git show HEAD:.repoMetrics/metrics.json > tmp_merge/ours_metrics.json 2>/dev/null || echo '{}' > tmp_merge/ours_metrics.json
          git show origin/${{ github.event.pull_request.base.ref }}:.repoMetrics/metrics.json > tmp_merge/theirs_metrics.json 2>/dev/null || echo '{}' > tmp_merge/theirs_metrics.json

          bash tools/merge-metrics.sh \
            tmp_merge/base_metrics.json \
            tmp_merge/ours_metrics.json \
            tmp_merge/theirs_metrics.json

          mv tmp_merge/ours_metrics.json .repoMetrics/metrics.json

      - name: Merge usageCounts
        run: |
          mkdir -p tmp_merge
          git show ${{ steps.mergebase.outputs.MERGE_BASE }}:.repoMetrics/usageCounts.json > tmp_merge/base_usage.json 2>/dev/null || echo '{}' > tmp_merge/base_usage.json
          git show HEAD:.repoMetrics/usageCounts.json > tmp_merge/ours_usage.json 2>/dev/null || echo '{}' > tmp_merge/ours_usage.json
          git show origin/${{ github.event.pull_request.base.ref }}:.repoMetrics/usageCounts.json > tmp_merge/theirs_usage.json 2>/dev/null || echo '{}' > tmp_merge/theirs_usage.json

          node tools/sumUsageCounts.js tmp_merge/base_usage.json tmp_merge/ours_usage.json tmp_merge/theirs_usage.json .repoMetrics/usageCounts.json

      - name: Merge searchHistory
        run: |
          mkdir -p tmp_merge
          git show ${{ steps.mergebase.outputs.MERGE_BASE }}:.repoMetrics/searchHistory > tmp_merge/base_history.txt 2>/dev/null || echo '' > tmp_merge/base_history.txt
          git show HEAD:.repoMetrics/searchHistory > tmp_merge/ours_history.txt 2>/dev/null || echo '' > tmp_merge/ours_history.txt
          git show origin/${{ github.event.pull_request.base.ref }}:.repoMetrics/searchHistory > tmp_merge/theirs_history.txt 2>/dev/null || echo '' > tmp_merge/theirs_history.txt

          bash tools/merge-history.sh \
            tmp_merge/base_history.txt \
            tmp_merge/ours_history.txt \
            tmp_merge/theirs_history.txt

          mv tmp_merge/ours_history.txt .repoMetrics/searchHistory

      - name: Merge noResultQueries
        run: |
          mkdir -p tmp_merge
          git show ${{ steps.mergebase.outputs.MERGE_BASE }}:.repoMetrics/noResultQueries > tmp_merge/base_no_results.txt 2>/dev/null || echo '' > tmp_merge/base_no_results.txt
          git show HEAD:.repoMetrics/noResultQueries > tmp_merge/ours_no_results.txt 2>/dev/null || echo '' > tmp_merge/ours_no_results.txt
          git show origin/${{ github.event.pull_request.base.ref }}:.repoMetrics/noResultQueries > tmp_merge/theirs_no_results.txt 2>/dev/null || echo '' > tmp_merge/theirs_no_results.txt

          bash tools/merge-no-results.sh \
            tmp_merge/base_no_results.txt \
            tmp_merge/ours_no_results.txt \
            tmp_merge/theirs_no_results.txt

          mv tmp_merge/ours_no_results.txt .repoMetrics/noResultQueries

      - name: Merge agentInfo Index
        run: |
          mkdir -p tmp_merge
          git show ${{ steps.mergebase.outputs.MERGE_BASE }}:.agentInfo/index.md > tmp_merge/base_index.txt 2>/dev/null || echo '' > tmp_merge/base_index.txt
          git show HEAD:.agentInfo/index.md > tmp_merge/ours_index.txt 2>/dev/null || echo '' > tmp_merge/ours_index.txt
          git show origin/${{ github.event.pull_request.base.ref }}:.agentInfo/index.md > tmp_merge/theirs_index.txt 2>/dev/null || echo '' > tmp_merge/theirs_index.txt

          bash tools/merge-agentinfo-index.sh \
            tmp_merge/base_index.txt \
            tmp_merge/ours_index.txt \
            tmp_merge/theirs_index.txt

          mv tmp_merge/ours_index.txt .agentInfo/index.md

      - name: Merge agentInfo Detailed Index
        run: |
          mkdir -p tmp_merge
          git show ${{ steps.mergebase.outputs.MERGE_BASE }}:.agentInfo/index-detailed.md > tmp_merge/base_index_detailed.txt 2>/dev/null || echo '' > tmp_merge/base_index_detailed.txt
          git show HEAD:.agentInfo/index-detailed.md > tmp_merge/ours_index_detailed.txt 2>/dev/null || echo '' > tmp_merge/ours_index_detailed.txt
          git show origin/${{ github.event.pull_request.base.ref }}:.agentInfo/index-detailed.md > tmp_merge/theirs_index_detailed.txt 2>/dev/null || echo '' > tmp_merge/theirs_index_detailed.txt

          bash tools/merge-agentinfo-index.sh \
            tmp_merge/base_index_detailed.txt \
            tmp_merge/ours_index_detailed.txt \
            tmp_merge/theirs_index_detailed.txt

          mv tmp_merge/ours_index_detailed.txt .agentInfo/index-detailed.md

      - name: Merge agentInfo Notes
        run: |
          mkdir -p tmp_merge
          NOTES_FILES=$( \
            { git ls-tree -r --name-only ${{ steps.mergebase.outputs.MERGE_BASE }} .agentInfo/notes; \
              git ls-tree -r --name-only HEAD .agentInfo/notes; \
              git ls-tree -r --name-only origin/${{ github.event.pull_request.base.ref }} .agentInfo/notes; \
            } | grep '\.md$' | sort -u \
          )

          for FILE in $NOTES_FILES; do
            SAFE_NAME=$(echo "$FILE" | tr '/' '_')

            git show ${{ steps.mergebase.outputs.MERGE_BASE }}:"$FILE" > tmp_merge/base_"$SAFE_NAME" 2>/dev/null || echo '' > tmp_merge/base_"$SAFE_NAME"
            git show HEAD:"$FILE" > tmp_merge/ours_"$SAFE_NAME" 2>/dev/null || echo '' > tmp_merge/ours_"$SAFE_NAME"
            git show origin/${{ github.event.pull_request.base.ref }}:"$FILE" > tmp_merge/theirs_"$SAFE_NAME" 2>/dev/null || echo '' > tmp_merge/theirs_"$SAFE_NAME"

            bash tools/merge-agentinfo-notes.sh \
              tmp_merge/base_"$SAFE_NAME" \
              tmp_merge/ours_"$SAFE_NAME" \
              tmp_merge/theirs_"$SAFE_NAME"

            cp tmp_merge/ours_"$SAFE_NAME" "$FILE"
          done

      - name: Commit merged changes
        run: |
          git add .repoMetrics/metrics.json .repoMetrics/usageCounts.json .repoMetrics/searchHistory .agentInfo/index.md .agentInfo/index-detailed.md $(git ls-files .agentInfo/notes)
          if ! git diff --cached --quiet; then
            git commit -m "Auto-merge .repoMetrics and .agentInfo"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "No changes detected in repoMetrics or agentInfo"
          fi
