name: prebuild
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  node-prebuild:
    runs-on: ubuntu-latest

    # ---------- 1  Check out and set up Node ----------
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'          

    # ---------- 2  Install deps once ----------
    - name: Install dependencies
      run: npm ci

    # ---------- 4  Cache node_modules + any build artefacts ----------
    - name: Save node_modules and dist/
      uses: actions/cache@v4.2.3
      with:
        path: |
          node_modules
        key: |
          ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    # ---------- 5  Publish as artefact for other jobs ----------
    - name: Upload build cache
      uses: actions/upload-artifact@v4.6.2
      with:
        name: node_cache
        path: |
          node modules
        if-no-files-found: error
