name: Sync search history

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Fetch master history
        run: |
          git fetch origin master
          git show origin/master:.searchHistory > base_history || touch base_history
      - run: npm run agent-update-searchhistory base_history .searchHistory
      - run: npm run agent-update-searchmetrics
      - name: Commit and push if changed
        run: |
          if ! git diff --quiet -- .searchHistory .searchMetrics; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add .searchHistory .searchMetrics/metrics.json
            git commit -m "chore: sync search history"
            git push origin HEAD:${{ github.head_ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
