name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/download-artifact@v4
        with: {name: build-cache}
      - run: npm run check-undefined
      - run: npm run lint
      - run: npm test
