name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Sync tools from master
        run: |
          git fetch origin master
          git checkout origin/master -- tools
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run agent-update-searchmetrics 
      - run: npm run agent-update-searchhistory
      - run: git add .
      - run: npm run format
      - run: git diff --exit-code
      - run: npm run check-undefined
      - run: npm run lint
      - run: npm run depcheck
      - run: npm test
      - run: npm run coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
